#! /bin/bash
# ~/.bash_profile
#Start dwm
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then 
	if ! startx; then 
		echo "Failed to start startx"
		read -p "Press enter to continue"
	fi
fi

[[ -f ~/.bashrc ]] && . ~/.bashrc
